version: '3.8'

services:
  mysql-db-post:
    image: mysql:8.0
    container_name: mysql-db-post
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-1:/var/lib/mysql

  mysql-db-review:
    image: mysql:8.0
    container_name: mysql-db-review
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviewservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"  # Gebruik een andere poort om conflicten te voorkomen
    volumes:
      - mysql-data-2:/var/lib/mysql

volumes:
  mysql-data-1:
  mysql-data-2:
